// src/components/Testcases.test.ts
export const validUsers = [
    { username: 'user1@example.com', password: 'Password123!' },
    { username: 'admin@example.com', password: 'Admin@2024' },
    { username: 'test.user@example.com', password: 'TestPass1$' },
    { username: 'hello@domain.org', password: 'HelloWorld9#' },
    { username: 'demo@sample.net', password: 'Demo1234!' },
    { username: 'valid1@alpha.com', password: 'Alpha123!' },
    { username: 'valid2@beta.com', password: 'Beta321@' },
    { username: 'john.doe@mail.com', password: 'Johndoe2023#' },
    { username: 'jane.doe@xyz.net', password: 'JaneDoe@123' },
    { username: 'contact@service.org', password: 'Contact99!' },
    { username: 'user10@test.com', password: 'StrongPass1!' },
    { username: 'alpha@domain.com', password: 'Zebra123$' },
    { username: 'beta@secure.com', password: 'Secured#89' },
    { username: 'gamma@alpha.org', password: 'Gamma321!' },
    { username: 'test123@demo.io', password: 'Test@1234' },
    { username: 'user.name@provider.net', password: 'ValidPass8@' },
    { username: 'user.lastname@mail.org', password: 'Lastname#9' },
    { username: 'feedback@portal.com', password: 'Feedback@2024' },
    { username: 'support@alpha.net', password: 'Support123!' },
    { username: 'admin.root@root.org', password: 'Root@Access1' },
    { username: 'user23@domain.com', password: 'Userpass@23' },
    { username: 'check@verify.io', password: 'Verify123@' },
    { username: 'form@entry.org', password: 'Entry#2024' },
    { username: 'login@testmail.com', password: 'LoginPass1!' },
    { username: 'tester@qa.net', password: 'QA_Tester@1' },
    { username: 'build@ci.org', password: 'BuildMe9#' },
    { username: 'system@server.com', password: 'Server1!' },
    { username: 'hello@world.com', password: 'World#1234' },
    { username: 'x@y.z', password: 'MiniMail9!' },
    { username: 'edge.case@limit.co', password: 'EdgeCase123!' },
];
export const invalidUsers = [
    { username: '', password: '' },
    { username: 'invalid-email', password: '123' },
    { username: 'user@domain.com', password: 'short' },
    { username: 'noatsymbol.com', password: 'Password1' },
    { username: 'bad@format', password: 'noNumbers!' },
    { username: 'missingdomain@', password: 'ValidPass1!' },
    { username: 'user@site', password: 'abc' },
    { username: 'justtext', password: 'JustText123!' },
    { username: 'user@domain.com', password: '      ' },
    { username: '@nodomain.com', password: 'Pass@123' },
    { username: 'missing@dot', password: 'Valid123#' },
    { username: 'valid@email.com', password: 'weak' },
    { username: ' ', password: 'NoEmail1!' },
    { username: 'email@domain.', password: 'Pass@123' },
    { username: 'email@@domain.com', password: 'Double@123' },
    { username: 'test@.com', password: 'MissingStart9!' },
    { username: 'user@domain.com', password: '' },
    { username: '', password: 'OnlyPass123!' },
    { username: 'wrong@space .com', password: 'Space123!' },
    { username: 'comma,email@domain.com', password: 'Comma@123' },
    { username: 'pipe|name@domain.com', password: 'Pipe#123' },
    { username: 'angle<email>@domain.com', password: 'Angle@123' },
    { username: 'quote"email@domain.com', password: 'Quote@123' },
    { username: 'semi;colon@domain.com', password: 'Semi@123' },
    { username: 'back\\slash@domain.com', password: 'Slash@123' },
    { username: 'colon:name@domain.com', password: 'Colon@123' },
    { username: 'tab\tuser@domain.com', password: 'Tab@123' },
    { username: 'newline\nuser@domain.com', password: 'Newline@123' },
    { username: 'admin@domain.com', password: '12345678' }, // no special
    { username: 'test@domain.com', password: 'PASSWORD!' }, // no lowercase
];
